# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: 'frontend'

- script: |
   echo "Copy dependencies to dist"
   cd frontend
   mkdir src/dist
   mkdir src/dist/lib
   mv node_modules/antd/dist/antd.min.css src/dist/lib/antd.min.css
   mv node_modules/react/umd/react.production.min.js src/dist/lib/react.development.js
   mv node_modules/react-dom/umd/react-dom.production.min.js src/dist/lib/react-dom.development.js
  displayName: 'Command Line Script'

- task: CopyFiles@2
  displayName: 'Copy File to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/frontend/src'
    Contents: |
     dist/**/*
     index.html
     App.css
    TargetFolder: '$(System.DefaultWorkingDirectory)/dist'

- task: ArchiveFiles@2
  displayName: 'Archive $(System.DefaultWorkingDirectory)/dist'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Open-KB-Front-Drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifactName: Open-KB-Front-Drop
