CREATE TABLE IF NOT EXISTS Board (id BINARY(16) NOT NULL, description varchar(255), title varchar(255), PRIMARY KEY (id))
CREATE TABLE IF NOT EXISTS Card (id BINARY(16) NOT NULL, description varchar(255), index integer NOT NULL, title varchar(255), list_id BINARY(16) NOT NULL, PRIMARY KEY (id))
CREATE TABLE IF NOT EXISTS List (id BINARY(16) NOT NULL, index integer NOT NULL, title varchar(255), board_id BINARY(16) NOT NULL, PRIMARY KEY (id))
ALTER TABLE Card ADD CONSTRAINT IF NOT EXISTS fkCardList FOREIGN KEY (list_id) REFERENCES List ON DELETE CASCADE
ALTER TABLE List ADD CONSTRAINT IF NOT EXISTS fkListBoard FOREIGN KEY (board_id) REFERENCES Board ON DELETE CASCADE
